### ISSUE TITLE
PgPartitionManager::Time::process cannot be used while specifying the db parameter

### ISSUE THREAD

**Issue by nickpwhite** [honeybadger-io/pg_partition_manager#1]
Since the `process` method passes one argument to `new`, it's impossible to specify the `db` (or `start`) parameter to `new`. Passing a hash causes the `partition` argument to contain the entire hash. I have a solution in mind that I can implement if you are interested.

Let me know if you need any more information, cheers.

**Comment by stympy** [comment]
Yeah, I’d be happy to take a look at it. Thanks!

**Comment by nickpwhite** [comment]
This PR addresses this issue https://github.com/honeybadger-io/pg_partition_manager/pull/2
